id: 2025-chevalier-differed-spontaneous-dissociative
title: 'Differed spontaneous dissociative symptoms following the use of esketamine intranasal spray in
  a patient suffering from treatment-resistant depression: a case report'
authors:
- Chevalier L
- Bulteau S
- Cheval L
- Charron J
- Sauvaget A
- Laurin A
first_author: Chevalier L
journal: International clinical psychopharmacology
year: 2025
volume: '40'
issue: '1'
pages: 37-40
doi: 10.1097/YIC.0000000000000527
pmid: '38277263'
type: Case report
topics:
- 术后谵妄与认知功能障碍
tags: []
evidence_level: na
oa_status: unknown
abstract: Intranasal esketamine is used in France for treatment-resistant depression. Dissociative symptoms
  are common side effects during treatment sessions. We report a case of delayed spontaneous dissociative
  symptoms following esketamine administration. A 20-year-old female with treatment-resistant depression
  received esketamine treatment. Dissociative symptoms occurred during sessions and persisted at a distance,
  often accompanied by anxiety. Delayed dissociative phenomena disappeared within the fourth week of treatment
  by esketamine. The literature mainly discusses dissociation during esketamine treatment sessions, with
  limited data on differed spontaneous episodes. Three hypotheses are discussed concerning the mechanism
  of occurrence of these dissociative phenomena, including esketamine's direct effect, central nervous
  system sensitization, and anxiety-induced dissociation. We present the first case of differed spontaneous
  dissociative effects after intranasal esketamine administration for treatment-resistant depression.
  Our main hypothesis suggests that esketamine may act as a 'pattern' for dissociative experiences, heightening
  the patient's ability to discern these phenomena during other instances of dissociation, such as acute
  anxiety attacks. Further research is needed to validate this hypothesis.
url: https://doi.org/10.1097/YIC.0000000000000527
pdf: null
language: en
status: reviewed
added_by: '@fanting1273-jpg'
added_date: '2026-09-21'
updated_date: '2026-09-21'
relevance: 3
