id: 2026-ahmad-difficult-airway-society
title: Difficult Airway Society 2025 guidelines for management of unanticipated difficult tracheal intubation
  in adults
authors:
- Ahmad I
- El-Boghdadly K
- Iliff H
- Dua G
- Higgs A
- Huntington M
- Mir F
- Nouraei SAR
- O'Sullivan EP
- Patel A
- Rivett K
- McNarry AF
first_author: Ahmad I
journal: British journal of anaesthesia
year: 2026
volume: '136'
issue: '1'
pages: 283-307
doi: 10.1016/j.bja.2025.10.006
pmid: '41203471'
type: Guideline
topics:
- 困难气道
tags: []
evidence_level: na
oa_status: unknown
abstract: Advances in our understanding and practice of airway management necessitate contemporary guidelines
  for tracheal intubation. The Difficult Airway Society (DAS) therefore produced recommendations to improve
  the efficacy and safety of tracheal intubation. We conducted a systematic review and a three-round Delphi
  process to formulate multidisciplinary, evidence-based, expert consensus recommendations. We invited
  20 external experts to guide recommendations on emergency front-of-neck airway and engaged DAS members
  and 16 international airway experts to provide feedback. Twelve members of the guidelines group participated
  in 65 meetings over 3 years, and 1241 papers were included after a systematic review. Sixty-five recommendations
  were made in relation to tracheal intubation. These included airway assessment and planning; peroxygenation;
  postintubation care; rapid sequence induction and intubation; the physiologically difficult airway;
  obesity; human factors; point-of-care ultrasound; documentation; and education and training. We maintain
  the concept of a linear algorithm encompassing tracheal intubation (Plan A); supraglottic airway device
  ventilation (Plan B); facemask ventilation (Plan C); and emergency front-of-neck airway (Plan D). The
  recommendations prioritise continuous oxygen delivery throughout airway management; maximising the likelihood
  of successful tracheal intubation at the first attempt; confirmation of ventilation with waveform capnography;
  progressing through the algorithm in the event of failure; multidisciplinary teamwork; and ongoing education
  and training. These guidelines are designed to support clinicians in delivering airway management that
  prioritises efficacy and safety. Overall, we emphasise the importance of maximising the chances of success,
  rather than the avoidance and management of failure, to improve outcomes for patients undergoing airway
  management.
url: https://doi.org/10.1016/j.bja.2025.10.006
pdf: null
language: en
status: draft
added_by: '@zhaokaixuan97-arch'
added_date: '2026-09-09'
updated_date: '2026-09-09'
relevance: 3
