id: 2026-cn-v3-263
title: 颊针疗法对无痛超声胃镜检查中麻醉效果的影响
authors:
- 林静 左友波 李妍妍 杨思琦 + 位作者
first_author: 林静 左友波 李妍妍 杨思琦 + 位作者
journal: 临床麻醉学杂志
year: 2026
volume: ''
issue: ''
pages: ''
doi: ''
pmid: ''
type: Other
topics:
- 颊针疗法
- 术后镇痛
tags:
- postoperative;nausea_vomiting
evidence_level: na
oa_status: unknown
abstract: 目的 探讨颊针疗法对无痛超声胃镜检查中麻醉效果的影响。方法 选择2024年3—6月接受超声胃镜检查的患者,年龄18~79岁,ASAⅠ—Ⅲ级。采用随机数字表法将患者分为两组:颊针组和对照组。颊针组于摆好体位后,在右侧面颊部颈穴、肩胛带穴、背穴、腰穴和腰背穴行颊针疗法,并留针至检查结束;对照组不予颊针治疗。随后两组进行静脉麻醉和超声胃镜检查。主要指标为术中丙泊酚用量。次要指标包括麻黄碱使用情况、苏醒时间、离室时间,内镜医师、麻醉科医师、患者满意度评分。不良反应包括术中低血压、呛咳、呃逆、体动以及术后嗜睡、恶心呕吐等。结果共纳入患者68例,每组34例。与对照组比较,颊针组术中丙泊酚用量明显减少,麻黄碱使用率明显降低,苏醒时间和离室时间明显缩短,内镜医师、麻醉科医师和患者满意率明显升高(P<0.05)。结论
  颊针疗法可降低无痛超声胃镜检查过程中丙泊酚用量,缩短患者苏醒时间和离室时间,提高患者满意度。
url: https://www.cqvip.com/doc/journal/7202908872
pdf: null
language: zh
status: draft
added_by: 颊针综述
added_date: '2026-09-09'
updated_date: '2026-09-09'
relevance: 3
