id: 2024-cn-v3-149
title: 颊针疗法对膝骨关节炎患者疼痛及肢体功能的作用研究
authors:
- 罗忠明 李西海
first_author: 罗忠明 李西海
journal: 山西医药杂志
year: 2024
volume: ''
issue: ''
pages: ''
doi: ''
pmid: ''
type: Observational
topics:
- 颊针疗法
tags:
- pain_general;knee
evidence_level: na
oa_status: unknown
abstract: 目的分析膝骨关节炎患者采用颊针疗法对促进其疼痛缓解及肢体功能改善所发挥的作用。方法将膝骨关节炎患者120例随机分成对照组和观察组,对照组采用常规治疗,观察组联合颊针疗法,比较2组临床疗效及治疗前、治疗1个月后、治疗3个月后关节功能障碍、膝关节主动活动度、被动活动度及生活质量改善情况,对比2组治疗后不良反应。结果观察组临床治疗总有效率高于对照组(P0.05),治疗后观察组具有更低的ODI评分及VAS评分,具有更高的Lysholm评分(P0.05),治疗后观察组患者主动活动度、被动活动度及生活质量评分均高于对照组(P<0.05)。观察组患者不良反应总发生率更低(P<0.05)。结论膝骨关节炎患者采用颊针疗法可促进膝关节功能改善,可显著减轻患者疼痛感,治疗安全,不良反应少。
url: https://www.cqvip.com/doc/journal/7112957644
pdf: null
language: zh
status: draft
added_by: 颊针综述
added_date: '2026-09-09'
updated_date: '2026-09-09'
relevance: 3
