id: 2024-cn-v3-154
title: 颊针疗法联合丙泊酚在宫腔镜手术中麻醉与镇痛的应用效果
authors:
- 王晓芳 王慧颖 梁鼎天 李志元 + 位作者
first_author: 王晓芳 王慧颖 梁鼎天 李志元 + 位作者
journal: 中国当代医药
year: 2024
volume: ''
issue: ''
pages: ''
doi: ''
pmid: ''
type: Other
topics:
- 颊针疗法
- 术后镇痛
tags:
- pain_general;postoperative;nausea_vomiting;gynecology_other
evidence_level: na
oa_status: unknown
abstract: 目的探讨颊针疗法联合丙泊酚在宫腔镜手术中的麻醉与镇痛效果。方法选取2023年4月至2023年7月北京中医药大学深圳医院(龙岗)收治的90例择期行静脉全身麻醉下宫腔镜手术的患者作为研究对象,按随机数字表法分为对照组(30例)、舒芬太尼组(30例)和颊针组(30例)。对照组采用单纯丙泊酚的静脉全身麻醉方案,颊针组采用颊针疗法联合丙泊酚的静脉全身麻醉方案,舒芬太尼组采用术中舒芬太尼复合丙泊酚的静脉全身麻醉方案。比较三组患者在入室时(T0)、麻醉诱导前(T1)、意识消失时(T2)、宫颈扩张进镜时(T3)和意识恢复时(T4)的平均动脉压(MAP)、心率(HR)、经皮动脉血氧饱和度(SpO2),术中不良反应发生、丙泊酚用量、苏醒时间、定向力恢复时间、术后疼痛评分和术后恶心呕吐(PONV)的发生情况。结果三组T0、T1、T2、T3和T4时刻的MAP、HR及SpO2组间比较,差异无统计学意义(P>0.05)。颊针组苏醒时间和定向力恢复时间均早于对照组,差异有统计学意义(P0.05)。结论妇科宫腔镜手术中应用颊针疗法有助于缓解术中不良反应及术后疼痛,可作为宫腔患者手术的辅助方法,值得临床推广应用。
url: https://www.cqvip.com/doc/journal/7112714517
pdf: null
language: zh
status: draft
added_by: 颊针综述
added_date: '2026-09-09'
updated_date: '2026-09-09'
relevance: 3
