id: 2025-wang-evidence-acupoint-stimulation-primary
title: 'Clinical Evidence of Acupoint Stimulation for Primary Dysmenorrhea: A Systematic Review and Updated
  Meta-Analysis.'
authors:
- Wang Y
- Liu L
- Wu X
- Wu Y
- Qin R
- Wang M
- Zhou B
- Sun J
- Song Y
- Zhang M
- Li M
- Yu L.
first_author: Wang Y
journal: Journal of pain research
year: 2025
volume: ''
issue: ''
pages: ''
doi: 10.2147/jpr.s533585
pmid: ''
type: Meta-analysis
topics:
- 颊针疗法
tags:
- pain_general;dysmenorrhea
evidence_level: na
oa_status: unknown
abstract: 'Purpose: Meridian-based acupoint stimulation is increasingly used for primary dysmenorrhea
  (PD), yet its evidence remains inconsistent. This systematic review aims to evaluate efficacy and safety
  of both invasive and noninvasive acupoint stimulation for PD through analysis of randomized controlled
  trials (RCTs).Methods: The PROSPERO registration number is CRD42024586857. PubMed, Excerpta Medica Database
  (Embase), Allied and Complementary Medicine Database (AMED), Cochrane Central Register of Controlled
  Trials (CENTRAL), Web of Science, Scopus, VIP Database, China National Knowledge Infrastruct'
url: https://doi.org/10.2147/jpr.s533585
pdf: null
language: en
status: draft
added_by: 颊针综述
added_date: '2026-09-09'
updated_date: '2026-09-09'
relevance: 3
