id: 2025-guo-efficacy-safety-buccal-acupuncture
title: 'Efficacy and safety of buccal acupuncture for pain management: A systematic review and meta-analysis.'
authors:
- Guo L
- Jia T
- Yang Y
- Feng H
- Jiang P.
first_author: Guo L
journal: Complementary therapies in medicine
year: 2025
volume: ''
issue: ''
pages: ''
doi: 10.1016/j.ctim.2025.103297
pmid: ''
type: Meta-analysis
topics:
- 颊针疗法
tags:
- pain_general
evidence_level: na
oa_status: unknown
abstract: 'OBJECTIVE: The objective of this study is to investigate the efficacy and safety of buccal
  acupuncture (BA) therapy for pain management through meta-analysis and systematic review. METHODS: A
  systematic search was conducted across eight databases (PubMed, Web of Science, Embase, Cochrane Library,
  etc) to identify randomized controlled trials (RCTs) evaluating the efficacy of BA in pain management.
  The search timeframe encompassed records form each database''s inception through January 25, 2025. The
  Cochrane Risk of Bias Tool was utilized to assess the methodological quality of the included stud'
url: https://doi.org/10.1016/j.ctim.2025.103297
pdf: null
language: en
status: draft
added_by: 颊针综述
added_date: '2026-09-09'
updated_date: '2026-09-09'
relevance: 3
