id: 2016-peltoniemi-ketamine-review-clinical
title: 'Ketamine: A Review of Clinical Pharmacokinetics and Pharmacodynamics in Anesthesia and Pain Therapy'
authors:
- Peltoniemi MA
- Hagelberg NM
- Olkkola KT
- Saari TI
first_author: Peltoniemi MA
journal: Clinical pharmacokinetics
year: 2016
volume: '55'
issue: '9'
pages: 1059-77
doi: 10.1007/s40262-016-0383-6
pmid: '27028535'
type: Review
topics:
- 氯胺酮
tags: []
evidence_level: na
oa_status: unknown
abstract: Ketamine is a phencyclidine derivative, which functions primarily as an antagonist of the N-methyl-D-aspartate
  receptor. It has no affinity for gamma-aminobutyric acid receptors in the central nervous system. Ketamine
  shows a chiral structure consisting of two optical isomers. It undergoes oxidative metabolism, mainly
  to norketamine by cytochrome P450 (CYP) 3A and CYP2B6 enzymes. The use of S-ketamine is increasing worldwide,
  since the S(+)-enantiomer has been postulated to be a four times more potent anesthetic and analgesic
  than the R(-)-enantiomer and approximately two times more effective than the racemic mixture of ketamine.
  Because of extensive first-pass metabolism, oral bioavailability is poor and ketamine is vulnerable
  to pharmacokinetic drug interactions. Sublingual and nasal formulations of ketamine are being developed,
  and especially nasal administration produces rapid maximum plasma ketamine concentrations with relatively
  high bioavailability. Ketamine produces hemodynamically stable anesthesia via central sympathetic stimulation
  without affecting respiratory function. Animal studies have shown that ketamine has neuroprotective
  properties, and there is no evidence of elevated intracranial pressure after ketamine dosing in humans.
  Low-dose perioperative ketamine may reduce opioid consumption and chronic postsurgical pain after specific
  surgical procedures. However, long-term analgesic effects of ketamine in chronic pain patients have
  not been demonstrated. Besides analgesic properties, ketamine has rapid-acting antidepressant effects,
  which may be useful in treating therapy-resistant depressive patients. Well-known psychotomimetic and
  cognitive adverse effects restrict the clinical usefulness of ketamine, even though fewer psychomimetic
  adverse effects have been reported with S-ketamine in comparison with the racemate. Safety issues in
  long-term use are yet to be resolved.
url: https://doi.org/10.1007/s40262-016-0383-6
pdf: null
language: en
status: draft
added_by: 氯胺酮检索
added_date: '2026-09-09'
updated_date: '2026-09-09'
relevance: 4
