id: 2025-cn-buccal-meta-analysis
title: 颊针疗法治疗颈-腰源性疼痛有效性的meta分析
authors:
- 张可京 李明婧 赵瑜 张艺 + 位作者
first_author: 张可京 李明婧 赵瑜 张艺 + 位作者
journal: 北京医学
year: 2025
volume: ''
issue: ''
pages: ''
doi: ''
pmid: ''
type: Meta-analysis
topics:
- 颊针疗法
tags:
- pain_general
evidence_level: na
oa_status: unknown
abstract: 目的探讨颊针疗法治疗颈-腰源性疼痛的有效性。方法选取建库至2024年9月20日中国知网、万方数据库、维普数据库、The Cochrane Library、PubMed和荷兰医学文献等数据库公开发表的关于颊针治疗颈-腰源性疼痛的RCT研究,对所有文献进行整理和分析,并使用Cochrane偏倚风险评估工具对文献进行质量评估,应用Stata
  18.0统计软件对提取数据进行meta分析。结果共检索85篇文献,最终纳入10篇文献,涉及899例患者,其中对照组(常规治疗方式)449例,联合组(对照组基础上仅加用颊针疗法或仅用颊针疗法)450例。其中4篇文献质量为A级、6篇文献质量为B级。Meta分析结果显示,试验组临床有效率(RR=0.16,95%CI:0.10~0.22,P<0.001,I2=17.70%)、视觉模拟评分法评分(RR=-1.41,95%CI:-2.00~-0.83,P<0.001,I2=94.54%)或颈痛量表评分(RR=-5.20,95%CI:-6.93~-3.47,P<0.001,I2=0.00%)降低幅度高于对照组,差异均有统计学意义(P<0.05)。结论颊针疗法可提高颈-腰源性疼痛患者的临床有效率,降低疼痛评分,减轻疼痛程度。
url: https://www.cqvip.com/doc/journal/7200922913
pdf: null
language: zh
status: draft
added_by: 颊针综述
added_date: '2026-09-09'
updated_date: '2026-09-09'
relevance: 3
