id: 2025-cn-v3-204
title: 颊针疗法对改善子宫全切术后应激及胃肠反应的应用研究
authors:
- 马志敏 邢凤娟
first_author: 马志敏 邢凤娟
journal: 中国疗养医学
year: 2025
volume: ''
issue: ''
pages: ''
doi: ''
pmid: ''
type: RCT
topics:
- 颊针疗法
- 术后镇痛
tags:
- pain_general;postoperative;gynecology_other
evidence_level: na
oa_status: unknown
abstract: 目的 观察颊针疗法对改善子宫全切术患者术后应激反应及胃肠反应的应用价值。方法 本研究为前瞻性研究,经双盲法抽取开封市妇产医院2022年1月至2024年2月收治的100例行子宫全切术患者为研究对象,应用电脑随机分组法生成随机序列,并进行分配隐藏后,将入组患者分别列为常规组(50例)和颊针组(50例),常规组予以常规全身麻醉,颊针组采用颊针疗法辅助全身麻醉,比较两组患者围术期血流动力学、围术期疼痛情况、术后应激指标及胃肠不良反应发生情况。结果
  在不同麻醉方案下,颊针组诱导后5 min(T1)心率(HR)及平均动脉压(MAP)与常规组差异无统计学意义(P>0.05);颊针组插管时(T2)、术毕时(T3)的HR分别为(77.69±10.24)次/min、(75.33±10.21)次/min,均低于常规组(83.23±10.46)次/min、(80.44±10.27)次/min,MAP分别为(110.25±20.43)mmHg(1mmHg=0.133kPa)、(109.45±20.49)mmHg,均低于常规组(126.33±20.37)mmHg、(124.14±20.45)mmHg,P<0.05;颊针组术中丙泊酚用量、瑞芬太尼用量、术后30
  min时的视觉模拟疼痛量表(VAS)评分、术后静脉自控镇痛泵(PCIA)按压次数分别为(30.23±5.16)mg、(1.22±0.34)mg、(2.7
url: https://www.cqvip.com/doc/journal/7200726729
pdf: null
language: zh
status: draft
added_by: 颊针综述
added_date: '2026-09-09'
updated_date: '2026-09-09'
relevance: 3
