id: 2026-cn-v3-271
title: 颊针疗法用于治疗慢性失眠的疗效及其对炎症因子水平的影响
authors:
- 黄俊祥 陈景晖 程秋菊 郭欣莹 + 位作者
first_author: 黄俊祥 陈景晖 程秋菊 郭欣莹 + 位作者
journal: 广东医学
year: 2026
volume: ''
issue: ''
pages: ''
doi: ''
pmid: ''
type: RCT
topics:
- 颊针疗法
tags:
- insomnia
evidence_level: na
oa_status: unknown
abstract: 目的观察颊针疗法治疗慢性失眠的疗效及其对炎症因子水平的影响。方法将60例诊断为慢性失眠的患者随机分为两组(n=30):颊针疗法治疗组(B组)采用颊针疗法,每周2次;对照组(C组)口服艾司唑仑片1mg,每晚1次;两组均治疗4周。记录两组患者治疗前后入睡时间、睡眠时间、睡眠效率、日间功能障碍及匹兹堡睡眠质量指数(Pittsburgh
  Sleep QualityIndex,PSQI)检测患者治疗前后血清炎症因子TNF-α、IL-6及IL-1β水平。记录两组患者治疗后不良反应发生情况。结果与治疗前比较,两组患者治疗后入睡时间缩短、睡眠时间延长、睡眠效率提高、日间功能障碍减少,PSQI总分均下降,差异均有统计学意义(P0.05);两组患者治疗后血清炎症因子TNF-α、IL-6及IL-1β水平均下降,差异有统计学意义(P0.05)。结论颊针疗法可有效治疗慢性失眠,降低慢性失眠患者体内炎症因子水平,且无不良反应,值得临床推广。
url: https://www.cqvip.com/doc/journal/7203290380
pdf: null
language: zh
status: draft
added_by: 颊针综述
added_date: '2026-09-09'
updated_date: '2026-09-09'
relevance: 3
