id: 2025-wang-cheek-acupuncture-reduces-postoperative
title: 'Cheek Acupuncture Reduces Postoperative Nausea and Vomiting in Patients Undergoing Laparoscopic
  Gynecological Surgery: A Randomized Controlled Trial.'
authors:
- Wang L
- Zou X
- Wu L
- Jin Z
- Hu S
- Zhu X
- Li X.
first_author: Wang L
journal: Journal of minimally invasive gynecology
year: 2025
volume: ''
issue: ''
pages: ''
doi: 10.1016/j.jmig.2025.01.011
pmid: ''
type: RCT
topics:
- 颊针疗法
- 术后镇痛
tags:
- pain_general;postoperative;nausea_vomiting;gynecology_other
evidence_level: na
oa_status: unknown
abstract: 'Objective: Cheek acupuncture, a recently established microneedle therapy, has been proven to
  effectively reduce pain, but its potential antiemetic effects remain unconfirmed. Thus, This study aimed
  to compare the antiemetic efficacy of cheek acupuncture with ondansetron and evaluate the cumulative
  effect in patients undergoing laparoscopic gynecological surgery.Design: A single-center randomized
  controlled trial.Setting: A university teaching hospital.Patients: A Total of 150 Adult patients who
  underwent laparoscopic gynecological surgery between July 2023 and December 2023.Interventions: Chee'
url: https://doi.org/10.1016/j.jmig.2025.01.011
pdf: null
language: en
status: draft
added_by: 颊针综述
added_date: '2026-09-09'
updated_date: '2026-09-09'
relevance: 3
