id: 2024-cn-v3-136
title: 颊针在剖宫产围术期的应用研究
authors:
- 牟伟才 柴福全 张振红 王同海 + 位作者
first_author: 牟伟才 柴福全 张振红 王同海 + 位作者
journal: 中外医疗
year: 2024
volume: ''
issue: ''
pages: ''
doi: ''
pmid: ''
type: Other
topics:
- 颊针疗法
- 术后镇痛
tags:
- pain_general;postoperative
evidence_level: na
oa_status: unknown
abstract: 目的探讨颊针在剖宫产围术期的应用效果。方法前瞻性随机选取2022年3—12月寿光市人民医院收治的80例接受剖宫产术产妇为研究对象,用随机数表法分为对照组和观察组,各40例。对照组使用术后静脉自控镇痛,观察组剖宫产完成后,先行颊针,其余同对照组,比较两组患者术后致痛物质P物质(Sub⁃stance
  P,SP)水平,术后6 h、术后24 h及术后48 h疼痛视觉模拟(Visual Analog Scale for Pain,VAS)评分变化情况,不良反应总发生率。结果观察组术后致痛物质SP水平低于对照组,差异有统计学意义(P<0.05);观察组术后VAS评分低于对照组,差异有统计学意义(P<0.05);观察组不良反应总发生率低于对照组,差异有统计学意义(P<0.05)。结论颊针用于剖宫产术后疼痛者,对降低机体致痛物质水平,缓解疼痛程度,减少不良反应等有积极意义。
url: https://www.cqvip.com/doc/journal/7112102088
pdf: null
language: zh
status: draft
added_by: 颊针综述
added_date: '2026-09-09'
updated_date: '2026-09-09'
relevance: 3
