id: 2024-cn-60
title: 颊针治疗神经根型颈椎病60例临床观察
authors:
- 于力楠 赵海鸿 娄译文 张彦辉 + 位作者
first_author: 于力楠 赵海鸿 娄译文 张彦辉 + 位作者
journal: 辽宁中医杂志
year: 2024
volume: ''
issue: ''
pages: ''
doi: ''
pmid: ''
type: RCT
topics:
- 颊针疗法
tags:
- pain_general;neck_shoulder
evidence_level: na
oa_status: unknown
abstract: 目的观察颊针治疗神经根型颈椎病的临床疗效。方法将60例患者随机分为治疗组和对照组各30例,治疗组采取颊针疗法,取颈穴、背穴、手穴,均为患侧面颊部取穴;对照组采用刮痧疗法,取华佗夹脊穴、督脉、手三阳经络循行区域、阿是穴,均为双侧取穴。观察两组患者治疗前后疼痛评分[视觉模拟评分法(visual
  analog scale,VAS)]、颈椎症状量表改善情况及临床疗效。结果治疗组临床治疗有效率为96.66%(29/30),明显高于对照组,差异有统计学意义(P<0.05)。治疗组VAS评分明显低于对照组,差异具有统计学意义(P<0.05);治疗组颈椎病症状量表评分明显高于对照组,差异具有统计学意义(P<0.05)。结论颊针治疗神经根型颈椎病疗效值得肯定,而且效果明显优于刮痧治疗。
url: https://www.cqvip.com/doc/journal/7112254893
pdf: null
language: zh
status: draft
added_by: 颊针综述
added_date: '2026-09-09'
updated_date: '2026-09-09'
relevance: 3
