id: 2025-chen-sub-anesthetic-doses-esketamine
title: Effects of sub-anesthetic doses of esketamine on postoperative sleep disturbance and pain in patients
  undergoing lumbar interbody fusion-A randomized, double-blind, placebo-controlled, two-center trial
authors:
- Chen Z
- Gao Y
- Gao C
- Zhang Y
- Zhang L
- Zhang H
- Wu Q
- Jin Y
- Guo N
- Liu L
- Cong P
- Jin Y
first_author: Chen Z
journal: Anaesthesia, critical care & pain medicine
year: 2025
volume: '44'
issue: '5'
pages: '101567'
doi: 10.1016/j.accpm.2025.101567
pmid: '40523523'
type: RCT
topics:
- 氯胺酮
- 术后镇痛
tags: []
evidence_level: na
oa_status: unknown
abstract: 'BACKGROUND: Postoperative sleep disturbance (PSD) is a common postoperative complication that
  significantly impacts patients'' recovery, particularly after lumbar surgery.

  METHODS: This two-center, double-blind, placebo-controlled randomized trial was conducted between June
  6, 2024, and November 26, 2024, in two hospitals in China. A total of 80 patients participated in this
  study and were randomly assigned to the esketamine group (n = 40) or the placebo group (n = 40). Patients
  in the esketamine group received 0.2 mg kg-¹ of esketamine for anesthesia induction, with a maintenance
  rate of 0.02 mg kg-¹ h-¹, followed by 1 mg kg-¹ of esketamine as an adjuvant in patient-controlled intravenous
  analgesia for 48 h after surgery. Saline was given to the placebo group of patients. The primary outcome
  of this study was the incidence of PSD on postoperative day (POD) 1. PSD was defined as a Numeric Rating
  Scale-sleep score of 6 or higher or an Athens Insomnia Scale score of 6 points or higher.

  RESULTS: The incidence of PSD on POD 1 was significantly lower in the esketamine group compared to the
  placebo group (33% vs. 67%; P = 0.003). The Visual Analog Scale (VAS)-pain score at rest was lower in
  the esketamine group compared to the placebo group at 1, 3, and 6 h after surgery (P <  0.05). The VAS-pain
  score with movement was also lower in the esketamine group than the placebo group at 1, 3, 6, and 24
  h after surgery (P <  0.05). Furthermore, the Quality of Recovery-15 (QoR-15) scores were significantly
  higher in the esketamine group than in the placebo group on POD 1 (107 [103-117] vs. 99 [96-108]; P = 
  0.005) and POD 3 (130 [122-136] vs. 124 [117-127]; P =  0.003).

  CONCLUSION: Sub-anesthetic doses of esketamine can reduce the incidence of PSD on POD 1, reduce postoperative
  pain, and improve QoR.

  CLINICAL TRIAL REGISTRATION: Chinese Clinical Trial Registry https://www.chictr.org.cn, ChiCTR2400083156.'
url: https://doi.org/10.1016/j.accpm.2025.101567
pdf: null
language: en
status: draft
added_by: 氯胺酮检索
added_date: '2026-09-09'
updated_date: '2026-09-09'
relevance: 4
