id: 2019-wiegele-caudal-epidural-blocks
title: 'Caudal epidural blocks in paediatric patients: a review and practical considerations'
authors:
- Wiegele M
- Marhofer P
- Lönnqvist PA
first_author: Wiegele M
journal: British journal of anaesthesia
year: 2019
volume: '122'
issue: '4'
pages: 509-517
doi: 10.1016/j.bja.2018.11.030
pmid: '30857607'
type: Review
topics:
- 氯胺酮
tags: []
evidence_level: na
oa_status: open
abstract: Caudal epidural blockade in children is one of the most widely administered techniques of regional
  anaesthesia. Recent clinical studies have answered major pharmacodynamic and pharmacokinetic questions,
  thus providing the scientific background for safe and effective blocks in daily clinical practice and
  demonstrating that patient selection can be expanded to range from extreme preterm births up to 50 kg
  of body weight. This narrative review discusses the main findings in the current literature with regard
  to patient selection (sub-umbilical vs mid-abdominal indications, contraindications, low-risk patients
  with spinal anomalies); anatomical considerations (access problems, age and body positioning, palpation
  for needle insertion); technical considerations (verification of needle position by ultrasound vs landmarks
  vs 'whoosh' or 'swoosh' testing); training and equipment requirements (learning curve, needle types,
  risk of tissue spreading); complications and safety (paediatric regional anaesthesia, caudal blocks);
  local anaesthetics (bupivacaine vs ropivacaine, risk of toxicity in children, management of toxic events);
  adjuvant drugs (clonidine, dexmedetomidine, opioids, ketamine); volume dosing (dermatomal reach, cranial
  rebound); caudally accessed lumbar or thoracic anaesthesia (contamination risk, verifying catheter placement);
  and postoperative pain. Caudal blocks are an efficient way to offer perioperative analgesia for painful
  sub-umbilical interventions. Performed on sedated children, they enable not only early ambulation, but
  also periprocedural haemodynamic stability and spontaneous breathing in patient groups at maximum risk
  of a difficult airway. These are important advantages over general anaesthesia, notably in preterm babies
  and in children with cardiopulmonary co-morbidities. Compared with other techniques of regional anaesthesia,
  a case for caudal blocks can still be made.
url: https://doi.org/10.1016/j.bja.2018.11.030
pdf: null
language: en
status: draft
added_by: 氯胺酮检索
added_date: '2026-09-09'
updated_date: '2026-09-09'
relevance: 4
