id: 2022-yavi-ketamine-treatment-depression
title: 'Ketamine treatment for depression: a review'
authors:
- Yavi M
- Lee H
- Henter ID
- Park LT
- Zarate CA Jr
first_author: Yavi M
journal: Discover mental health
year: 2022
volume: '2'
issue: '1'
pages: '9'
doi: 10.1007/s44192-022-00012-3
pmid: '35509843'
type: Review
topics:
- 氯胺酮
tags: []
evidence_level: na
oa_status: open
abstract: This manuscript reviews the clinical evidence regarding single-dose intravenous (IV) administration
  of the novel glutamatergic modulator racemic (R,S)-ketamine (hereafter referred to as ketamine) as well
  as its S-enantiomer, intranasal esketamine, for the treatment of major depressive disorder (MDD). Initial
  studies found that a single subanesthetic-dose IV ketamine infusion rapidly (within one day) improved
  depressive symptoms in individuals with MDD and bipolar depression, with antidepressant effects lasting
  three to seven days. In 2019, esketamine received FDA approval as an adjunctive treatment for treatment-resistant
  depression (TRD) in adults. Esketamine was approved under a risk evaluation and mitigation strategy
  (REMS) that requires administration under medical supervision. Both ketamine and esketamine are currently
  viable treatment options for TRD that offer the possibility of rapid symptom improvement. The manuscript
  also reviews ketamine's use in other psychiatric diagnoses-including suicidality, obsessive-compulsive
  disorder, post-traumatic stress disorder, substance abuse, and social anxiety disorder-and its potential
  adverse effects. Despite limited data, side effects for antidepressant-dose ketamine-including dissociative
  symptoms, hypertension, and confusion/agitation-appear to be tolerable and limited to around the time
  of treatment. Relatively little is known about ketamine's longer-term effects, including increased risks
  of abuse and/or dependence. Attempts to prolong ketamine's effects with combined therapy or a repeat-dose
  strategy are also reviewed, as are current guidelines for its clinical use. In addition to presenting
  a novel and valuable treatment option, studying ketamine also has the potential to transform our understanding
  of the mechanisms underlying mood disorders and the development of novel therapeutics.
url: https://doi.org/10.1007/s44192-022-00012-3
pdf: null
language: en
status: draft
added_by: 氯胺酮检索
added_date: '2026-09-09'
updated_date: '2026-09-09'
relevance: 4
