id: 2025-cn-14
title: 颊针疗法用于安宁疗护患者癌症疼痛控制14例疗效分析
authors:
- 顾梦婷 夏燕飞 单汉民
first_author: 顾梦婷 夏燕飞 单汉民
journal: 浙江医学
year: 2025
volume: ''
issue: ''
pages: ''
doi: ''
pmid: ''
type: Observational
topics:
- 颊针疗法
tags:
- pain_general;insomnia;anxiety_depression;cancer_pain
evidence_level: na
oa_status: unknown
abstract: 目的探讨颊针疗法在安宁疗护患者癌症疼痛控制中的疗效。方法回顾性选取2024年4月至12月接受安宁疗护的终末期癌痛患者14例,1次/d,5次为1疗程。取面颊部对应全身各部位疼痛的缩影系统精确对应定位,浅刺法角度15~30,深度3~9
  mm适度留针,达到控制疼痛治疗目的。比较患者治疗前、治疗第1周、治疗第2周数字评分(NRS)法评分、医院焦虑抑郁量表(HADS)评分、匹兹堡睡眠质量指数(PSQI)评分、欧洲癌症研究与治疗组织生命质量测定量表评分。结果患者治疗第1周、第2周NRS法评分、HADS评分均较治疗前下降,差异均有统计学意义(均P0.05)。结论颊针疗法对安宁疗护患者的癌症疼痛控制有一定的临床效果。
url: https://www.cqvip.com/doc/journal/7201513321
pdf: null
language: zh
status: draft
added_by: 颊针综述
added_date: '2026-09-09'
updated_date: '2026-09-09'
relevance: 3
