id: 2025-cn-v3-227
title: 颊针联合鼻炎通窍片治疗变应性鼻炎临床研究
authors:
- 钟丽娟 彭燏琴 王宏碧 张顺
- + 位作者
first_author: 钟丽娟 彭燏琴 王宏碧 张顺
journal: 实用中医药杂志
year: 2025
volume: ''
issue: ''
pages: ''
doi: ''
pmid: ''
type: RCT
topics:
- 颊针疗法
tags:
- rhinitis
evidence_level: na
oa_status: unknown
abstract: 目的:观察颊针联合鼻炎通窍片治疗变应性鼻炎(AR)的临床效果。方法:68例随机分为观察组和对照组每各34例。对照组予鼻炎通窍片治疗,观察组予颊针联合鼻炎通窍片治疗。结果:总有效率观察组高于对照组(P<0.05),中医证候积分、VAS、RQLQ、HAMD、HAMA、PSQI评分、IL-4、IL-8、EOS、总IgE降低及IL-10提高观察组幅度大于对照组(P<0.05)。结论:颊针联合鼻炎通窍片治疗AR疗效较好。
url: https://www.cqvip.com/doc/journal/7201093247
pdf: null
language: zh
status: draft
added_by: 颊针综述
added_date: '2026-09-09'
updated_date: '2026-09-09'
relevance: 3
