id: 2025-cn-v3-222
title: 颊针联合柴胡加龙骨牡蛎汤治疗肝郁脾虚型失眠的临床研究
authors:
- 胡宗华 李健 穆建宁 杜少庆
first_author: 胡宗华 李健 穆建宁 杜少庆
journal: 世界睡眠医学杂志
year: 2025
volume: ''
issue: ''
pages: ''
doi: ''
pmid: ''
type: RCT
topics:
- 颊针疗法
tags:
- insomnia
evidence_level: na
oa_status: unknown
abstract: 目的:探讨颊针联合柴胡加龙骨牡蛎汤对肝郁脾虚型失眠的影响。方法:选取2023年1月至2024年1月在日照市东港区妇幼保健院就诊的肝郁脾虚型失眠患者80例作为研究对象,按照随机数字表法随机分为观察组和对照组,每组40例。对照组予以柴胡加龙骨牡蛎汤治疗,观察组在此基础上应用颊针治疗。比较2组临床疗效、睡眠质量、慢波睡眠时间、快速眼动睡眠时间。结果:观察组临床疗效优于对照组;治疗1个月后、3个月后、6个月后,观察组匹兹堡睡眠指数量表评分(PSQI)比对照组低;治疗1个月后,观察组慢波及快速眼动睡眠时间长于对照组,差异有统计学意义(P<0.05)。结论:肝郁脾虚型失眠患者联合应用颊针、柴胡加龙骨牡蛎汤,可提升治疗效果及睡眠质量,延长慢波睡眠时间、快速眼动睡眠时间。
url: https://www.cqvip.com/doc/journal/7201124534
pdf: null
language: zh
status: draft
added_by: 颊针综述
added_date: '2026-09-09'
updated_date: '2026-09-09'
relevance: 3
