id: 2025-dagher-opioid-free-anesthesia-bariatric
title: 'Opioid-free anesthesia in bariatric surgery: a prospective randomized controlled trial'
authors:
- Dagher C
- Mattar R
- Aoun M
- Tohme J
- Naccache N
- Jabbour H
first_author: Dagher C
journal: European journal of medical research
year: 2025
volume: '30'
issue: '1'
pages: '320'
doi: 10.1186/s40001-025-02565-9
pmid: '40269993'
type: RCT
topics:
- 氯胺酮
tags: []
evidence_level: na
oa_status: open
abstract: 'BACKGROUND: Bariatric surgeries are increasingly used to manage obesity, presenting significant
  perioperative challenges, especially with opioid use. Opioid-Free Anesthesia (OFA) is a multimodal technique
  to address these issues. This study aims to compare the effects of OFA and traditional Opioid-Based
  Anesthesia (OBA) on postoperative morphine consumption, hemodynamics, pain, postoperative nausea and
  vomiting (PONV), sedation, and patient satisfaction in bariatric surgery.

  METHODS: A prospective controlled study was conducted in the operating room of a tertiary university
  hospital. It included patients aged between 18 and 65 years undergoing bariatric surgery. 58 obese patients
  were divided into two groups: 32 received OBA and 26 received OFA. The OFA regimen included lidocaine,
  ketamine, magnesium sulfate, dexmedetomidine, and dexamethasone. Main outcome measures included postoperative
  morphine consumption in the Post-Anesthesia Care Unit (PACU), 24 and 48 h after surgery. Secondary outcomes
  included hemodynamic parameters, sedation score, pain score, presence of nausea and/or vomiting, and
  overall patient satisfaction evaluated at 48 h postoperatively or before hospital discharge were recorded.

  RESULTS: OFA significantly reduced postoperative morphine consumption (median dose of 8 mg vs.19 mg,
  p = 0.000). Visual analogue scale (VAS) scores for pain at rest, during movement, and during coughing
  were significantly lower in the OFA group. Both groups were hemodynamically stable perioperatively.
  There was no significant difference in PONV incidence or sedation levels between the groups in the PACU,
  24 and 48 h after surgery. Patient satisfaction was higher in the OFA group, with 65% reporting a satisfaction
  score of ≥ 8/10 compared to 28% in the OBA group.

  CONCLUSIONS: OFA reduces postoperative morphine consumption and improves pain management without compromising
  hemodynamic stability or increasing sedation. Furthermore, the incidence of PONV was not significantly
  different and overall patient satisfaction was higher with OFA. These findings support the use of OFA
  in bariatric surgery, despite the need for further studies with larger sample sizes.'
url: https://doi.org/10.1186/s40001-025-02565-9
pdf: null
language: en
status: draft
added_by: 氯胺酮检索
added_date: '2026-09-09'
updated_date: '2026-09-09'
relevance: 4
