id: 2026-zou-cheek-acupuncture-reduces-postoperative
title: 'Cheek Acupuncture Reduces Postoperative Sore Throat After Double-Lumen Endobronchial Intubation:
  A Randomized Controlled Trial.'
authors:
- Zou X
- Hu S
- Li X
- Zhu X
- Wang L
- Wu L.
first_author: Zou X
journal: Journal of pain research
year: 2026
volume: ''
issue: ''
pages: ''
doi: 10.2147/jpr.s604498
pmid: ''
type: RCT
topics:
- 颊针疗法
- 术后镇痛
tags:
- pain_general;postoperative;nausea_vomiting;sore_throat
evidence_level: na
oa_status: unknown
abstract: 'Purpose: Postoperative sore throat (POST) is highly prevalent following double-lumen endobronchial
  tube (DLT) intubation and negatively impacts recovery. Cheek acupuncture, a micro-needle therapy, provides
  targeted analgesia through specific acupoint stimulation. This study aimed to evaluate the efficacy
  of cheek acupuncture in mitigating POST in patients undergoing thoracoscopic lung surgery with DLT intubation.
  Patients and Methods: Eighty-eight patients were equally randomized to receive either cheek acupuncture
  (CA group) at bilateral cervical, upper energizer, and upper cervical points fo'
url: https://doi.org/10.2147/jpr.s604498
pdf: null
language: en
status: draft
added_by: 颊针综述
added_date: '2026-09-09'
updated_date: '2026-09-09'
relevance: 3
