id: 2025-cn-v3-219
title: 颊针联合右美托咪定对老年股骨近端髓内钉固定术患者术后睡眠质量及认知功能的影响
authors:
- 陈加胜 张琦
first_author: 陈加胜 张琦
journal: 临床医学研究与实践
year: 2025
volume: ''
issue: ''
pages: ''
doi: ''
pmid: ''
type: RCT
topics:
- 颊针疗法
- 术后镇痛
tags:
- pain_general;postoperative;insomnia;stroke_cognition
evidence_level: na
oa_status: unknown
abstract: 目的探究颊针联合右美托咪定在老年股骨近端髓内钉固定术患者中的应用效果。方法选择2023年1月至12月60例住院行股骨近端髓内钉固定术的老年患者为研究对象,根据入院顺序将其随机分为对照组(30例,右美托咪)和联合组(30例,颊针联合右美托咪定)。比较两组的应用效果。结果术后12、24、48、72
  h,联合组的疼痛数字评定量表(NRS)评分低于对照组(P<0.05)。术后24、48、72 h,联合组的匹兹堡睡眠质量指数(PSQI)评分低于对照组,简易精神状态检查量表(MMSE)评分高于对照组(P<0.05)。联合组的患者静脉自控镇痛(PCIA)首次按压时间晚于对照组,PCIA按压次数少于对照组,不良反应总发生率低于对照组(P<0.05)。术后24
  h,联合组的超敏C反应蛋白(hs-CRP)及白细胞介素-6(IL-6)水平低于对照组(P<0.05)。结论颊针联合右美托咪定应用在老年股骨近端髓内钉固定术患者中可取得显著疗效。
url: https://www.cqvip.com/doc/journal/7201829038
pdf: null
language: zh
status: draft
added_by: 颊针综述
added_date: '2026-09-09'
updated_date: '2026-09-09'
relevance: 3
