id: 2023-shan-buccal-acupuncture-combined-ultrasound-guided
title: Buccal acupuncture combined with ultrasound-guided dry needle-evoked inactivation of trigger points
  to treat cervical and shoulder girdle myofascial pain syndrome.
authors:
- Shan HH
- Chen HF
- Lu XH
- Zhang XM
- Liu SL
- Chang XL
- Ni HY
- Gou XJ.
first_author: Shan HH
journal: Journal of back and musculoskeletal rehabilitation
year: 2023
volume: ''
issue: ''
pages: ''
doi: 10.3233/bmr-220321
pmid: ''
type: RCT
topics:
- 颊针疗法
tags:
- pain_general;neck_shoulder;facial_palsy
evidence_level: na
oa_status: unknown
abstract: 'BACKGROUND: Myofascial pain syndrome (MPS) is a common disease with easy persistence and recurrence.
  In clinical practice, although many methods have been adopted to prevent and treat MPS, the control
  of MPS is still not satisfactory. OBJECTIVE: To compare the safety and effectiveness of buccal acupuncture,
  inactivation of trigger points (MTrPs), and their combination in the treatment of MPS. METHODS: Two
  hundred MPS patients in the pain clinic were randomly divided into four groups (n= 50) to receive oral
  drugs (Group A), oral drugs + buccal needle (Group B), oral drugs + MTrP inactivation (G'
url: https://doi.org/10.3233/bmr-220321
pdf: null
language: en
status: draft
added_by: 颊针综述
added_date: '2026-09-09'
updated_date: '2026-09-09'
relevance: 3
