id: 2024-cn-ponv
title: 持续输注利多卡因注射液联合颊针对降低腹腔镜全子宫切除术患者术后PONV发生率的影响
authors:
- 张继霞 曾情 巫华雄 曾鸣
first_author: 张继霞 曾情 巫华雄 曾鸣
journal: 医学信息
year: 2024
volume: ''
issue: ''
pages: ''
doi: ''
pmid: ''
type: Other
topics:
- 颊针疗法
- 术后镇痛
tags:
- postoperative;nausea_vomiting;gynecology_other
evidence_level: na
oa_status: unknown
abstract: 目的研究持续输注利多卡因注射液联合颊针对降低腹腔镜全子宫切除术患者术后恶心呕吐(PONV)发生率的影响。方法选取2022年5月-2023年8月我院接诊并收治行腹腔镜全子宫切除手术的72例患者为研究对象,两组均采用气管插管全麻,采用随机数字表法分为对照组(36例)和观察组(36例),对照组给予常规麻醉诱导,观察组麻醉诱导前给予颊针+持续输注利多卡因注射液。比较两组不同时间点恶心呕吐发生情况、舒适度评分(NVAS)、首次排气和排便时间、不良反应发生情况及治疗满意度。结果观察组麻醉苏醒期、术后2
  h、术后6 h、术后12 h恶心呕吐发生率均低于对照组(P0.05);观察组治疗满意度高于对照组(P<0.05)。结论持续输注利多卡因注射液联合颊针可有效降低腹腔镜全子宫切除术患者术后PONV发生率,提高患者治疗满意度,缩短胃肠功能恢复时间,改善患者舒适度,值得临床应用。
url: https://www.cqvip.com/doc/journal/7112988619
pdf: null
language: zh
status: draft
added_by: 颊针综述
added_date: '2026-09-09'
updated_date: '2026-09-09'
relevance: 3
