id: 2019-gustafsson-guidelines-perioperative-care
title: 'Guidelines for Perioperative Care in Elective Colorectal Surgery: Enhanced Recovery After Surgery
  (ERAS(®)) Society Recommendations: 2018'
authors:
- Gustafsson UO
- Scott MJ
- Hubner M
- Nygren J
- Demartines N
- Francis N
- Rockall TA
- Young-Fadok TM
- Hill AG
- Soop M
- de Boer HD
- Urman RD
- Chang GJ
- Fichera A
- Kessler H
- Grass F
- Whang EE
- Fawcett WJ
- Carli F
- Lobo DN
- Rollins KE
- Balfour A
- Baldini G
- Riedel B
- Ljungqvist O
first_author: Gustafsson UO
journal: World journal of surgery
year: 2019
volume: '43'
issue: '3'
pages: 659-695
doi: 10.1007/s00268-018-4844-y
pmid: '30426190'
type: Guideline
topics:
- 加速康复外科（ERAS）
- 指南与专家共识
tags: []
evidence_level: na
oa_status: unknown
abstract: 'BACKGROUND: This is the fourth updated Enhanced Recovery After Surgery (ERAS®) Society guideline
  presenting a consensus for optimal perioperative care in colorectal surgery and providing graded recommendations
  for each ERAS item within the ERAS® protocol.

  METHODS: A wide database search on English literature publications was performed. Studies on each item
  within the protocol were selected with particular attention paid to meta-analyses, randomised controlled
  trials and large prospective cohorts and examined, reviewed and graded according to Grading of Recommendations,
  Assessment, Development and Evaluation (GRADE) system.

  RESULTS: All recommendations on ERAS® protocol items are based on best available evidence; good-quality
  trials; meta-analyses of good-quality trials; or large cohort studies. The level of evidence for the
  use of each item is presented accordingly.

  CONCLUSIONS: The evidence base and recommendation for items within the multimodal perioperative care
  pathway are presented by the ERAS® Society in this comprehensive consensus review.'
url: https://doi.org/10.1007/s00268-018-4844-y
pdf: null
language: en
status: draft
added_by: 示例数据
added_date: '2026-09-09'
updated_date: '2026-09-09'
relevance: 5
