id: 2024-cn-v3-148
title: 颊针疗法对腹腔镜结肠癌根治术患者围术期镇痛效果的影响
authors:
- 周弋晖 朱美华 胡海青 牛聪 + 位作者
first_author: 周弋晖 朱美华 胡海青 牛聪 + 位作者
journal: 临床麻醉学杂志
year: 2024
volume: ''
issue: ''
pages: ''
doi: ''
pmid: ''
type: Other
topics:
- 颊针疗法
- 术后镇痛
tags:
- pain_general;postoperative;cancer_pain;nausea_vomiting
evidence_level: na
oa_status: unknown
abstract: 目的观察颊针疗法对腹腔镜结肠癌根治术患者围术期镇痛效果的影响。方法选择择期行腹腔镜结肠癌根治术的患者60例,男32例,女28例,年龄45~74岁,BMI 18.5~25.0 kg/m2,ASAⅡ或Ⅲ级。采用随机数字表法将患者分为两组:颊针组和对照组,每组30例。颊针组麻醉诱导前给予颊针疗法1次,术后每日上午9点行颊针疗法1次,每次留针30
  min,连续治疗3 d;对照组不行颊针治疗。记录术中丙泊酚、瑞芬太尼、术后48 h内舒芬太尼用量和镇痛泵按压次数。记录术后1、4、24、48 h VAS疼痛评分。分别于入室时及术后1、2、3 d采集静脉血,检测血浆C反应蛋白(CRP)、白细胞介素-6(IL-6)、肿瘤坏死因子-α(TNF-α)的浓度。记录术后48
  h内不良反应的发生情况。结果与对照组比较,颊针组术中丙泊酚、瑞芬太尼、术后48 h内舒芬太尼用量及镇痛泵按压次数明显减少(P<0.05),术后1、4、24、48 h VAS疼痛评分明显降低(P<0.05),术后1、2、3
  d CRP、IL-6、TNF-α浓度明显降低(P<0.05),术后48 h内恶心呕吐、喉痉挛及咽喉不适发生率明显降低(P<0.05)。结论对腹腔镜结肠癌根治术患者围术期运用颊针疗法,可以有效减轻疼痛,抑制炎症反应,减少术后不良反应。
url: https://www.cqvip.com/doc/journal/7112477471
pdf: null
language: zh
status: draft
added_by: 颊针综述
added_date: '2026-09-09'
updated_date: '2026-09-09'
relevance: 3
