id: 2023-cn-v3-102
title: 董氏奇穴联合颊针对全膝关节置换围术期多模式镇痛的临床研究
authors:
- 凌泽权 李阳 何勇 王兴龙
first_author: 凌泽权 李阳 何勇 王兴龙
journal: 针灸临床杂志
year: 2023
volume: ''
issue: ''
pages: ''
doi: ''
pmid: ''
type: RCT
topics:
- 颊针疗法
- 术后镇痛
tags:
- pain_general;postoperative;knee;nausea_vomiting
evidence_level: na
oa_status: unknown
abstract: 目的:观察董氏奇穴联合颊针在全膝关节置换(TKA)围术期多模式镇痛中的临床疗效。方法:将60例诊断为膝骨性关节炎患者随机分为对照组和研究组,每组各30例。对照组采用快速康复管理的多模式镇痛方式:股神经麻醉阻滞+静脉自控镇痛泵(PCIA)+术前2
  h、术后6 h分别给予0.1 g艾瑞昔布,服用7 d, 2次/d, 0.1 g/次;研究组在对照组基础上应用董氏奇穴联合颊针替代艾瑞昔布治疗,术前2 h、术后6 h应用董氏奇穴联合颊针,针刺7 d,
  1次/d, 1次40 min。通过观察比较两组患者的疼痛视觉模拟(VAS)评分、PCIA按压次数、膝关节美国特种外科医院(HSS)评分和术后不良反应来评价疗效。结果:研究组术后3 d、5 d与10 d的VAS评分低于对照组,差异具有统计学意义(P<0.05)。研究组术后7
  d、14 d的HSS评分优于对照组,差异具有统计学意义(P<0.05)。研究组在术后48 h内的PCIA按压次数、术后胃痛恶心呕吐等胃肠道不良反应发生次数低于对照组,差异具有统计学意义(P<0.05)。结论:董氏奇穴联合颊针对TKA术后患者的早期镇痛效果显著,可更快改善患者关节功能活动,能够减少药物使用,降低不良反应的发生率。
url: https://www.cqvip.com/doc/journal/7110784473
pdf: null
language: zh
status: draft
added_by: 颊针综述
added_date: '2026-09-09'
updated_date: '2026-09-09'
relevance: 3
