id: 2024-cn-v3-145
title: 颊针疗法在经皮椎体成形术术前镇痛中的应用研究
authors:
- 陈雄为 王萍 林江海 周一敏 + 位作者
first_author: 陈雄为 王萍 林江海 周一敏 + 位作者
journal: 浙江中医杂志
year: 2024
volume: ''
issue: ''
pages: ''
doi: ''
pmid: ''
type: Other
topics:
- 颊针疗法
- 术后镇痛
tags:
- pain_general;postoperative
evidence_level: na
oa_status: unknown
abstract: 经皮椎体成形术是治疗椎体压缩性骨折的有效手段,该类手术是将骨水泥注入压缩的椎体内,从而达到稳定椎体[1,2]、治疗疼痛的目的,具有手术时间短、治疗效果佳、术后康复快等优势。因此,笔者利用颊针疗法止痛的即时性作为经皮椎体成形术术前镇痛方式,探讨该模式下经皮椎体成形术中的镇痛疗效和安全性,现报道如下。
url: https://www.cqvip.com/doc/journal/7111726102
pdf: null
language: zh
status: draft
added_by: 颊针综述
added_date: '2026-09-09'
updated_date: '2026-09-09'
relevance: 3
