id: 2025-cn-v3-196
title: 针刺麻醉与颊针对老年髋部骨折术后应激反应及镇痛效果
authors:
- 周晓筠 徐金东 谭享业 林浩升 + 位作者
first_author: 周晓筠 徐金东 谭享业 林浩升 + 位作者
journal: 广东医学
year: 2025
volume: ''
issue: ''
pages: ''
doi: ''
pmid: ''
type: RCT
topics:
- 颊针疗法
- 术后镇痛
tags:
- pain_general;postoperative
evidence_level: na
oa_status: unknown
abstract: 目的探讨针刺麻醉与颊针分别应用于老年患者髋部手术后辅助镇痛,评价这两种方法对患者应激反应、术后镇痛效果以及术后并发症的影响。方法纳入2024年1—10月于广州中医药大学第一附属医院中山医院接受腰麻下单侧髋部手术的老年患者126例,随机分为3组:BA组、FA组和NA组,每组42例,最终115例完成试验(BA组38例,FA组39例,NA组38例)。3组患者手术后进入麻醉复苏室(麻醉复苏室)。BA组行百汇,双侧内关、曲池、合谷、足三里5个传统穴位针刺;FA组在与手术同侧的面颊部腰、骶、髋等穴位行针刺;NA组无任何针刺处理。观察并记录患者术后6
  h(T0)、12 h(T1)、24 h(T2)、48 h(T3)的血清去甲肾上腺素(norepinephrine,NE)、肾上腺素(epinephrine,EPI)、皮质醇(cortisol,COR)、血糖(blood
  glucose,BG),计算舒芬太尼累积用量及疼痛视觉模拟评分(visual analog scale,VAS)评分,观察术后肠道恢复时间及并发症发生率。结果BA组与FA组术后各时间点应激反应指标(NE、EPI、COR、BG)水平显著低于NA组(P<0.05);BA组与FA组术后48
  h舒芬太尼用量和VAS评分比NA组显著降低(P<0.05),且肠道恢复时间显著缩短(P<0.05)。术后并发症BA组与FA组显著少于NA组(P<0.0
url: https://www.cqvip.com/doc/journal/7202709405
pdf: null
language: zh
status: draft
added_by: 颊针综述
added_date: '2026-09-09'
updated_date: '2026-09-09'
relevance: 3
