id: 2024-johnston-ketamine-neuropsychiatric-disorders
title: 'Ketamine in neuropsychiatric disorders: an update'
authors:
- Johnston JN
- Kadriu B
- Kraus C
- Henter ID
- Zarate CA Jr
first_author: Johnston JN
journal: 'Neuropsychopharmacology : official publication of the American College of Neuropsychopharmacology'
year: 2024
volume: '49'
issue: '1'
pages: 23-40
doi: 10.1038/s41386-023-01632-1
pmid: '37340091'
type: Review
topics:
- 氯胺酮
tags: []
evidence_level: na
oa_status: open
abstract: 'The discovery of ketamine as a rapid-acting antidepressant led to a new era in the development
  of neuropsychiatric therapeutics, one characterized by an antidepressant response that occurred within
  hours or days rather than weeks or months. Considerable clinical research supports the use of-or further
  research with-subanesthetic-dose ketamine and its (S)-enantiomer esketamine in multiple neuropsychiatric
  disorders including depression, bipolar disorder, anxiety spectrum disorders, substance use disorders,
  and eating disorders, as well as for the management of chronic pain. In addition, ketamine often effectively
  targets symptom domains associated with multiple disorders, such as anxiety, anhedonia, and suicidal
  ideation. This manuscript: 1) reviews the literature on the pharmacology and hypothesized mechanisms
  of subanesthetic-dose ketamine in clinical research; 2) describes similarities and differences in the
  mechanism of action and antidepressant efficacy between racemic ketamine, its (S) and (R) enantiomers,
  and its hydroxynorketamine (HNK) metabolite; 3) discusses the day-to-day use of ketamine in the clinical
  setting; 4) provides an overview of ketamine use in other psychiatric disorders and depression-related
  comorbidities (e.g., suicidal ideation); and 5) provides insights into the mechanisms of ketamine and
  therapeutic response gleaned from the study of other novel therapeutics and neuroimaging modalities.'
url: https://doi.org/10.1038/s41386-023-01632-1
pdf: null
language: en
status: draft
added_by: 氯胺酮检索
added_date: '2026-09-09'
updated_date: '2026-09-09'
relevance: 4
