id: 2024-li-efficacy-acupuncture-therapy-combined
title: 'Clinical efficacy of acupuncture therapy combined with core muscle exercises in treating patients
  with chronic nonspecific low back pain: a systematic review and meta-analysis of randomized controlled
  trials.'
authors:
- Li X
- Zhai G
- Zhang H
- Li X
- Wu M
- Zhang S
- Cui J
- Tang Z
- Hu Z.
first_author: Li X
journal: Frontiers in medicine
year: 2024
volume: ''
issue: ''
pages: ''
doi: 10.3389/fmed.2024.1372748
pmid: ''
type: Meta-analysis
topics:
- 颊针疗法
tags:
- pain_general;low_back
evidence_level: na
oa_status: unknown
abstract: 'Introduction: This meta-analysis aimed to determine the clinical efficacy of acupuncture combined
  with core muscle exercises on pain and functional status in patients with chronic nonspecific low back
  pain.Methods: This study followed the Preferred Reporting Items for Systematic Reviews and meta-analysis
  criteria for systematic reviews and meta-analyses. Randomized controlled trials published till November
  2023 were searched in PubMed, Web of Science, Cochrane, Embase, China National Knowledge Infrastructure,
  Chinese Biomedical Literature, and Wanfang databases. The search strategy was related'
url: https://doi.org/10.3389/fmed.2024.1372748
pdf: null
language: en
status: draft
added_by: 颊针综述
added_date: '2026-09-09'
updated_date: '2026-09-09'
relevance: 3
