id: 2024-zhu-buccal-acupuncture-postoperative-analgesia
title: 'Effects of buccal acupuncture on postoperative analgesia in elderly patients undergoing laparoscopic
  radical gastrectomy: a randomized controlled trial.'
authors:
- Zhu DX
- Yang YL
- Yang L
- Zhao YY
- Xie YY
- Wang W
- Lv J
- Yu WY.
first_author: Zhu DX
journal: Frontiers in neurology
year: 2024
volume: ''
issue: ''
pages: ''
doi: 10.3389/fneur.2024.1408360
pmid: ''
type: RCT
topics:
- 颊针疗法
- 术后镇痛
tags:
- pain_general;postoperative
evidence_level: na
oa_status: unknown
abstract: 'Objective: This study aimed to evaluate the efficacy and safety of buccal acupuncture on postoperative
  analgesia, perioperative stress response and adverse events in elderly patients undergoing laparoscopic
  radical gastrectomy.Methods: It was a prospective, outcome assessor-blinded, randomized controlled trial,
  involving 90 patients aged 65-80 years who were treated with an elective laparoscopic radical gastrectomy.
  They were randomly assigned to buccal acupuncture group (Group B) and control group (Group C). Buccal
  acupuncture was applied to patients of Group B before the induction of general'
url: https://doi.org/10.3389/fneur.2024.1408360
pdf: null
language: en
status: draft
added_by: 颊针综述
added_date: '2026-09-09'
updated_date: '2026-09-09'
relevance: 3
