id: 2024-cn-v3-157
title: 颊针联合椎旁神经阻滞治疗胸背部带状疱疹后神经痛的疗效观察
authors:
- 蒋晨浩 张建楠 周红梅 李荣华 + 位作者
first_author: 蒋晨浩 张建楠 周红梅 李荣华 + 位作者
journal: 世界中医药
year: 2024
volume: ''
issue: ''
pages: ''
doi: ''
pmid: ''
type: RCT
topics:
- 颊针疗法
tags:
- pain_general;PHN
evidence_level: na
oa_status: unknown
abstract: 目的:观察颊针联合椎旁神经阻滞治疗胸背部带状疱疹后神经痛(PHN)的临床疗效。方法:选取2021年1月至2021年12月无锡市中医医院收治的PHN患者100例作为研究对象,按照随机数字表法随机分为对照组和观察组,每组50例。对照组采用基础药物配合椎旁神经阻滞治疗,观察组在对照组基础上联合颊针治疗。观察并记录2组患者治疗前及治疗1、2、3、4周后视觉模拟评分(VAS),治疗前后的健康调查简表(SF-36)评分、血清中神经元特异性烯醇化酶(NSE)水平、辅助T细胞1/2(Th1/Th2)水平、不良反应发生情况及总有效率。结果:治疗后2组患者VAS均低于治疗前,且观察组优于对照组(P0.05),观察组总有效率优于对照组(P<0.05)。结论:颊针联合椎旁神经阻滞治疗胸背部PHN效果显著,能有效缓解疼痛,提升患者治疗期间的生命质量,降低神经细胞损伤,提高免疫力。
url: https://www.cqvip.com/doc/journal/7112507378
pdf: null
language: zh
status: draft
added_by: 颊针综述
added_date: '2026-09-09'
updated_date: '2026-09-09'
relevance: 3
