id: 2020-fu-esketamine-nasal-spray
title: 'Esketamine Nasal Spray for Rapid Reduction of Major Depressive Disorder Symptoms in Patients Who
  Have Active Suicidal Ideation With Intent: Double-Blind, Randomized Study (ASPIRE I)'
authors:
- Fu DJ
- Ionescu DF
- Li X
- Lane R
- Lim P
- Sanacora G
- Hough D
- Manji H
- Drevets WC
- Canuso CM
first_author: Fu DJ
journal: The Journal of clinical psychiatry
year: 2020
volume: '81'
issue: '3'
pages: ''
doi: 10.4088/JCP.19m13191
pmid: '32412700'
type: RCT
topics:
- 氯胺酮
tags: []
evidence_level: na
oa_status: unknown
abstract: 'OBJECTIVE: To compare esketamine to placebo, each in addition to standard-of-care treatment,
  for rapidly reducing major depressive disorder symptoms, including suicidal ideation.

  METHODS: This phase 3, double-blind, multicenter study (ASPIRE I), conducted between June 2017 and December
  2018, enrolled 226 adults having major depressive disorder based on Diagnostic and Statistical Manual
  of Mental Disorders fifth edition (DSM-5) criteria, active suicidal ideation with intent, and need for
  psychiatric hospitalization. Patients were randomized 1:1 to esketamine 84 mg or placebo nasal spray
  twice-weekly for 4 weeks, each with comprehensive standard-of-care treatment (initial psychiatric hospitalization
  and newly initiated or optimized oral antidepressant[s] therapy). Change from baseline to 24 hours post-first
  dose in Montgomery-Asberg Depression Rating Scale (MADRS) total score (primary endpoint) was analyzed
  using analysis of covariance (ANCOVA), and change in Clinical Global Impression of Severity of Suicidality
  Revised version (CGI-SS-r; key secondary endpoint) score was analyzed using ANCOVA on ranks with treatment
  difference estimated using the Hodges-Lehmann estimate.

  RESULTS: Greater improvement in MADRS total score was observed with esketamine + standard-of-care versus
  placebo + standard-of-care at 24 hours (least-squares mean difference [SE]: -3.8 [1.39]; 95% CI, -6.56
  to -1.09; 2-sided P = .006), as well as at earlier (4 hours) and later time points during 4-week double-blind
  treatment. The difference between groups in the severity of suicidality was not statistically significant
  (median of treatment difference [95% CI]: 0.0 [-1.00 to 0.00]; 2-sided P = .107). The most common adverse
  events among esketamine-treated patients were dizziness, dissociation, headache, nausea, and somnolence.

  CONCLUSIONS: These findings demonstrate rapid and robust efficacy of esketamine nasal spray in reducing
  depressive symptoms in severely ill patients with major depressive disorder who have active suicidal
  ideation with intent.

  TRIAL REGISTRATION: ClinicalTrials.gov identifier: NCT03039192.'
url: https://doi.org/10.4088/JCP.19m13191
pdf: null
language: en
status: draft
added_by: 氯胺酮检索
added_date: '2026-09-09'
updated_date: '2026-09-09'
relevance: 4
