id: 2025-cn-v3-208
title: 颊针疗法对腹腔镜结直肠癌根治术患者苏醒期躁动的影响
authors:
- 张家敏 朱美华 牛聪 胡海青 + 位作者
first_author: 张家敏 朱美华 牛聪 胡海青 + 位作者
journal: 江苏医药
year: 2025
volume: ''
issue: ''
pages: ''
doi: ''
pmid: ''
type: RCT
topics:
- 颊针疗法
- 术后镇痛
tags:
- pain_general;postoperative;nausea_vomiting
evidence_level: na
oa_status: unknown
abstract: 目的 观察颊针疗法对腹腔镜结直肠癌根治术患者苏醒期躁动的影响。方法 择期全身麻醉下接受腹腔镜结直肠癌根治术患者60例,随机分为颊针组和对照组,每组30例。颊针组于麻醉诱导前针刺三焦穴、腰穴和骶穴,并留针,每隔5分钟行针1次,至手术结束起针。对照组不行颊针治疗。采用Riker镇静-躁动评分(SAS)评估苏醒期躁动发生情况,记录VAS疼痛评分;检测患者入室时、拔管后15min及术后1d时血浆IL-6、TNF-α浓度。记录患者围手术期丙泊酚、雷米芬太尼、舒芬太尼用量。观察患者恶心呕吐、呼吸抑制及苏醒延迟等不良反应的发生情况。结果
  与对照组比较,颊针组患者苏醒期SAS、VAS疼痛评分和苏醒期躁动发生率降低(P<0.05),围手术期丙泊酚、雷米芬太尼和舒芬太尼用量减少(P<0.05),拔管后15min血浆IL-6和TNF-α浓度降低(P<0.05)。颊针组术后恶心呕吐发生率低于对照组(10%vs.37%)(P<0.05)。结论
  颊针疗法可以有效减轻腹腔镜结直肠癌根治术患者的术后疼痛,抑制炎症反应,减少苏醒期躁动和术后恶心呕吐的发生。
url: https://www.cqvip.com/doc/journal/7200259620
pdf: null
language: zh
status: draft
added_by: 颊针综述
added_date: '2026-09-09'
updated_date: '2026-09-09'
relevance: 3
