id: 2018-schwenk-consensus-guidelines-use
title: Consensus Guidelines on the Use of Intravenous Ketamine Infusions for Acute Pain Management From
  the American Society of Regional Anesthesia and Pain Medicine, the American Academy of Pain Medicine,
  and the American Society of Anesthesiologists
authors:
- Schwenk ES
- Viscusi ER
- Buvanendran A
- Hurley RW
- Wasan AD
- Narouze S
- Bhatia A
- Davis FN
- Hooten WM
- Cohen SP
first_author: Schwenk ES
journal: Regional anesthesia and pain medicine
year: 2018
volume: '43'
issue: '5'
pages: 456-466
doi: 10.1097/AAP.0000000000000806
pmid: '29870457'
type: Guideline
topics:
- 氯胺酮
tags: []
evidence_level: na
oa_status: open
abstract: 'BACKGROUND: Ketamine infusions have been used for decades to treat acute pain, but a recent
  surge in usage has made the infusions a mainstay of treatment in emergency departments, in the perioperative
  period in individuals with refractory pain, and in opioid-tolerant patients. The widespread variability
  in patient selection, treatment parameters, and monitoring indicates a need for the creation of consensus
  guidelines.

  METHODS: The development of acute pain ketamine guidelines grew as a corollary from the genesis of chronic
  pain ketamine guidelines. The charge for the development of acute pain ketamine guidelines was provided
  by the Boards of Directors of both the American Society of Regional Anesthesia and Pain Medicine and
  the American Academy of Pain Medicine, who approved the document along with the American Society of
  Anesthesiologists'' Committees on Pain Medicine and Standards and Practice Parameters. The committee
  chair developed questions based on input from the committee during conference calls, which the committee
  then refined. Groups of 3 to 5 panel members and the committee chair were responsible for answering
  individual questions. After preliminary consensus was achieved, the entire committee made further revisions
  via e-mail and conference calls.

  RESULTS: Consensus guidelines were prepared in the following areas: indications, contraindications for
  acute pain and whether they differ from those for chronic pain, the evidence for the use of ketamine
  as an adjunct to opioid-based therapy, the evidence supporting patient-controlled ketamine analgesia,
  the use of nonparenteral forms of ketamine, and the subanesthetic dosage range and whether the evidence
  supports those dosages for acute pain. The group was able to reach consensus on the answers to all questions.

  CONCLUSIONS: Evidence supports the use of ketamine for acute pain in a variety of contexts, including
  as a stand-alone treatment, as an adjunct to opioids, and, to a lesser extent, as an intranasal formulation.
  Contraindications for acute pain are similar to those for chronic pain, partly based on the observation
  that the dosage ranges are similar. Larger studies evaluating different acute pain conditions are needed
  to enhance patient selection, determine the effectiveness of nonparenteral ketamine alternatives, define
  optimal treatment parameters, and develop protocols optimizing safety and access to care.'
url: https://doi.org/10.1097/AAP.0000000000000806
pdf: null
language: en
status: draft
added_by: 氯胺酮检索
added_date: '2026-09-09'
updated_date: '2026-09-09'
relevance: 4
