id: 2026-wang-cheek-acupuncture-stress-urinary
title: 'Effect of cheek acupuncture on stress urinary incontinence in menopausal women: a randomized clinical
  trial.'
authors:
- Wang D
- You Y
- Zhu Q
- Luo T
- Yang H
- Liu J
- Cheng F
- Nie G.
first_author: Wang D
journal: 'QJM : monthly journal of the Association of Physicians'
year: 2026
volume: ''
issue: ''
pages: ''
doi: 10.1093/qjmed/hcaf287
pmid: ''
type: RCT
topics:
- 颊针疗法
tags:
- urinary
evidence_level: na
oa_status: unknown
abstract: 'BACKGROUND: Stress urinary incontinence (SUI) affects quality of life and imposes healthcare
  burdens, particularly in postmenopausal women. While non-surgical interventions are recommended as first-line
  therapies, patient adherence remains a challenge. AIM: To compare the effectiveness of cheek acupuncture
  (CA) with PFMT for managing SUI in menopausal women. DESIGN AND METHODS: A randomized controlled trial
  in China assigned participants to CA (n = 51) or PFMT (n = 52) groups for a 12-week intervention, with
  a 4-week follow-up. The primary outcome were the change in the amount of urine leakage'
url: https://doi.org/10.1093/qjmed/hcaf287
pdf: null
language: en
status: draft
added_by: 颊针综述
added_date: '2026-09-09'
updated_date: '2026-09-09'
relevance: 3
