id: 2026-cn-2026
title: 颊针疗法围手术期应用专家共识(2026版)
authors:
- 甘肃省中医药学会围术期医学专业委员会 上海市中医药学会围术期医学分会 薛建军 宋建钢 + 位作者
first_author: 甘肃省中医药学会围术期医学专业委员会 上海市中医药学会围术期医学分会 薛建军 宋建钢 + 位作者
journal: 中华麻醉学杂志
year: 2026
volume: ''
issue: ''
pages: ''
doi: ''
pmid: ''
type: Other
topics:
- 颊针疗法
- 术后镇痛
tags:
- pain_general;postoperative
evidence_level: na
oa_status: unknown
abstract: 颊针疗法作为一种新型微针疗法,在围手术期应用中展现出独特优势。为规范颊针疗法在围手术期的临床应用,提高治疗安全性与有效性,甘肃省中医药学会围术期医学专业委员会、上海市中医药学会围术期医学分会、法国国际颊针学院组织相关领域专家制定了本共识。本共识在系统梳理国内外相关研究证据、总结临床实践经验的基础上,通过德尔菲法,经过多轮讨论与修订,形成15条推荐意见,内容涵盖颊针疗法围手术期操作流程、操作时机及穴位选择、应用有效性与安全性等方面,以期为临床医师提供颊针疗法围手术期应用的指导意见,更好地推广和应用颊针疗法,服务于围手术期患者。
url: https://www.cqvip.com/doc/journal/7204012603
pdf: null
language: zh
status: draft
added_by: 颊针综述
added_date: '2026-09-09'
updated_date: '2026-09-09'
relevance: 3
