id: 2026-cn-v3-275
title: 颊针联合康复训练治疗对前交叉韧带损伤重建术后康复的影响
authors:
- 董津含 杨英昕 于忠行 王成刚 + 位作者
first_author: 董津含 杨英昕 于忠行 王成刚 + 位作者
journal: 中国医药
year: 2026
volume: ''
issue: ''
pages: ''
doi: ''
pmid: ''
type: RCT
topics:
- 颊针疗法
- 术后镇痛
tags:
- pain_general;postoperative;knee
evidence_level: na
oa_status: unknown
abstract: 目的探讨颊针联合康复训练治疗对前交叉韧带损伤重建术后康复的影响。方法选择2023年2月至2025年2月于中国人民解放军北部战区总医院就诊的前交叉韧带损伤重建术后患者106例,采用区组随机化法随机分为对照组和观察组,各53例。2组治疗过程中各有4例患者未按时康复训练而剔除,2组各实际纳入49例患者。对照组给予康复训练治疗,观察组在对照组基础上给予颊针治疗。观察2组患者治疗前后主要疗效指标[膝关节Lysholm评分、国际膝关节文献委员会(IKDC)评分、疼痛视觉模拟量表评分、膝关节活动度]、次要疗效指标[膝关节功能(膝关节患侧肿胀值、大腿周径差值)、患侧膝关节伸膝及屈膝峰值力矩]及临床疗效。结果2组治疗后膝关节Lysholm评分、IKDC评分、膝关节活动度,患侧膝关节伸膝及屈膝峰值力矩均较治疗前升高/增大,且观察组均高于/大于对照组[膝关节Lysholm评分:(72±5)分比(66±7)分,IKDC评分:(80±7)分比(70±12)分,膝关节活动度外旋:(38.5±5.6)°比(30.6±6.1)°,内旋:(29.4±3.1)°比(25.5±3.3)°,屈伸:(121.9±18.2)°比(105.7±19.2)°,患侧膝关节伸膝峰值力矩:(46±8)N·m比(34±10)N·m,屈膝峰值力矩:(49±10)N·m比(37±11)N·m](均P<0.05)。2组治疗后疼痛视觉模拟量表评
url: https://www.cqvip.com/doc/journal/7202942787
pdf: null
language: zh
status: draft
added_by: 颊针综述
added_date: '2026-09-09'
updated_date: '2026-09-09'
relevance: 3
