id: 2024-yi-observation-90-cases-primary
title: 'Clinical observation on 90 cases of primary dysmenorrhea treated by buccal acupuncture therapy:
  a randomized controlled study.'
authors:
- Yi Y
- Huijun YE
- Huiling Z
- Lihua J.
first_author: Yi Y
journal: Journal of traditional Chinese medicine = Chung i tsa chih ying wen pan
year: 2024
volume: ''
issue: ''
pages: ''
doi: 10.19852/j.cnki.jtcm.20231110.001
pmid: ''
type: RCT
topics:
- 颊针疗法
tags:
- pain_general;dysmenorrhea
evidence_level: na
oa_status: unknown
abstract: 'Objective: To explore the short-term and long-term efficacy of buccal acupuncture therapy in
  the treatment of patients with primary dysmenorrhea (PD).Methods: A total of 90 patients with PD who
  were admitted to the Second Affiliated Hospital of Zhejiang University of Traditional Chinese Medicine
  from January 2020 to December 2021 were included in this study and randomly divided into three groups,
  including the observation group, the control group, and the placebo group, with 30 patients in each
  group. Patients in the observation group were treated according to the syndrome types of Traditional'
url: https://doi.org/10.19852/j.cnki.jtcm.20231110.001
pdf: null
language: en
status: draft
added_by: 颊针综述
added_date: '2026-09-09'
updated_date: '2026-09-09'
relevance: 3
