id: 2026-cn-v3-269
title: 颊针疗法对腹腔镜胆囊切除术患者术后肩痛的影响
authors:
- 蒋晨浩 蔡靓羽 张建楠 李绍烁 + 位作者
first_author: 蒋晨浩 蔡靓羽 张建楠 李绍烁 + 位作者
journal: 临床麻醉学杂志
year: 2026
volume: ''
issue: ''
pages: ''
doi: ''
pmid: ''
type: Other
topics:
- 颊针疗法
- 术后镇痛
tags:
- pain_general;postoperative;nausea_vomiting
evidence_level: na
oa_status: unknown
abstract: 目的 探讨术前行颊针疗法对腹腔镜胆囊切除术患者术后肩痛的影响。方法 选择行腹腔镜胆囊切除术患者,年龄18~70岁,BMI 18.5~28.0 kg/m2,ASAⅠ或Ⅱ级。采用随机数字表法将患者分为两组:颊针组和对照组。颊针组于麻醉诱导前行颊针干预(双侧头穴、颈穴、肩胛带穴、肩穴、上焦穴、中焦穴、下焦穴),留针40
  min;对照组未行颊针干预。两组麻醉诱导及维持方案一致。主要指标为术后48 h内肩痛的发生率。次要指标包括术中丙泊酚、瑞芬太尼用量,术后4、8、12、24及48 h的VAS疼痛评分,术后48 h内镇痛泵总按压次数、有效按压次数及补救镇痛率,术后肩痛持续时间大于12
  h的发生率,麻醉诱导前、术毕即刻及术后24 h的PaCO2以及血清炎性因子IL-6、TNF-α浓度。术后不良反应包括术后恶心、呕吐、头晕、腹胀。结果 共纳入患者126例,每组63例。与对照组比较,颊针组术中丙泊酚、瑞芬太尼用量明显降低,术后4、8、12及24
  h的VAS疼痛评分明显降低,镇痛泵总按压次数、有效按压次数及补救镇痛率明显降低,术后48 h肩痛和疼痛持续时间大于12 h的发生率明显降低,术毕即刻PaCO2明显降低,术毕即刻、术后24 h血清炎性因子IL-6、TNF-α浓度明显降低,术后恶心、呕吐发生率明显降低(P<0.05)。结论
  在腹腔镜胆囊手术麻醉诱导前行颊针疗法可以减少术中丙泊酚、瑞芬太尼用量,
url: https://www.cqvip.com/doc/journal/7203438602
pdf: null
language: zh
status: draft
added_by: 颊针综述
added_date: '2026-09-09'
updated_date: '2026-09-09'
relevance: 3
