id: 2025-chen-immediate-modulations-cheek-acupuncture
title: Immediate Modulations of Cheek Acupuncture on Brain Oscillations and Connectivity in Individuals
  With Chronic Pain.
authors:
- Chen X
- Tong S
- Zhu Y
- Xu T
- Guo X
- Zhong W.
first_author: Chen X
journal: 'IEEE transactions on neural systems and rehabilitation engineering : a publication of the IEEE
  Engineering in Medicine and Biology Society'
year: 2025
volume: ''
issue: ''
pages: ''
doi: 10.1109/tnsre.2025.3621122
pmid: ''
type: Other
topics:
- 颊针疗法
tags:
- pain_general
evidence_level: na
oa_status: unknown
abstract: Chronic pain challenges global healthcare due to its complexity and the limitations of current
  treatments. Cheek acupuncture (CA), which targets specific acupoints on the cheek based on the biological
  holographic model, has shown promise for immediate pain relief. Despite its efficacy across various
  clinical studies, the mechanisms underlying its analgesic effects remain unclear. In this study, through
  resting electroencephalography analysis of 37 participants with chronic pain before, during, and after
  CA therapy, we investigated the electrophysiological modulations underlying the immediate a
url: https://doi.org/10.1109/tnsre.2025.3621122
pdf: null
language: en
status: draft
added_by: 颊针综述
added_date: '2026-09-09'
updated_date: '2026-09-09'
relevance: 3
