id: 2025-cn-v3-206
title: 颊针疗法对老年患者腹腔镜胃癌根治术后镇痛的影响
authors:
- 朱冬雪 陈香香 谢亚运 汪伟 + 位作者
first_author: 朱冬雪 陈香香 谢亚运 汪伟 + 位作者
journal: 临床麻醉学杂志
year: 2025
volume: ''
issue: ''
pages: ''
doi: ''
pmid: ''
type: Other
topics:
- 颊针疗法
- 术后镇痛
tags:
- pain_general;postoperative;nausea_vomiting
evidence_level: na
oa_status: unknown
abstract: 目的观察麻醉诱导前颊针疗法对行腹腔镜胃癌根治术的老年患者术后镇痛效果与安全性的影响。方法选择择期行腹腔镜胃癌根治术的老年患者87例,男48例,女39例,年龄65~85岁,BMI 22~30
  kg/m2,ASAⅡ或Ⅲ级。采用随机数字表法将患者分为两组:颊针组(n=44)和对照组(n=43)。颊针组于麻醉诱导前行颊针疗法,留置30 min;对照组直接进行麻醉诱导。手术结束后行患者自控静脉镇痛,镇痛配方:舒芬太尼2.0μg/kg、帕洛诺司琼0.25
  mg加入生理盐水150 ml,负荷量5 ml,背景量2 ml/h,单次剂量1.5 ml。记录术中丙泊酚、瑞芬太尼和血管活性药物用量、术后苏醒时间、拔管时间和术后住院时间。记录术后2、6、24、48 h静息时VAS疼痛评分。记录术后48
  h内镇痛泵总按压次数、有效按压次数、舒芬太尼用量以及术后补救镇痛情况。记录术后48 h术后恶心呕吐(PONV)、嗜睡、呼吸抑制和皮肤瘙痒等不良反应的发生情况。结果与对照组比较,颊针组术中丙泊酚、瑞芬太尼和血管活性药物用量明显减少(P<0.05),术后苏醒时间、拔管时间和术后住院时间明显缩短(P<0.05),术后2、6、24
  h的静息时VAS疼痛评分明显降低(P<0.05),术后48 h内镇痛泵总按压次数、有效按压次数、舒芬太尼使用量、补救镇痛率和PONV发生率明显降低(P<0.05)。两组术后48 h嗜睡、呼吸
url: https://www.cqvip.com/doc/journal/7200319717
pdf: null
language: zh
status: draft
added_by: 颊针综述
added_date: '2026-09-09'
updated_date: '2026-09-09'
relevance: 3
