id: 2026-jia-cheek-acupuncture-can-improve
title: Cheek acupuncture can improve the depressive and anxious symptoms of patients with moderate depression
  disorders.
authors:
- Jia X
- Shen P
- Wang C
- Zhou G
- Zhou H
- Xu F
- Jiang S.
first_author: Jia X
journal: Complementary therapies in medicine
year: 2026
volume: ''
issue: ''
pages: ''
doi: 10.1016/j.ctim.2026.103383
pmid: ''
type: Basic science
topics:
- 颊针疗法
tags:
- neck_shoulder;anxiety_depression;stroke_cognition
evidence_level: na
oa_status: unknown
abstract: 'OBJECTIVE: Through a randomized controlled clinical trial, the clinical efficacy of cheek acupuncture
  therapy in treating patients with moderate depressive disorder and explored its neuroimaging mechanisms
  was evaluated. PATIENTS AND METHODS: This clinical study recruited participants with moderate depressive
  disorder who met the inclusion criteria and did not meet the exclusion criteria, admitted to the outpatient
  clinics of Zhejiang Provincial Hospital of Traditional Chinese Medicine''s Acupuncture and Mental Health
  Departments (September 2022 - May 2025). Participants were systematically ran'
url: https://doi.org/10.1016/j.ctim.2026.103383
pdf: null
language: en
status: draft
added_by: 颊针综述
added_date: '2026-09-09'
updated_date: '2026-09-09'
relevance: 3
