id: 2025-shen-long-term-acupuncture-primary
title: 'Long Term Effects of Acupuncture for Primary Dysmenorrhea: A Systematic Review and Meta-Analysis.'
authors:
- Shen X
- Liu S
- Chen H
- Wang W
- Fang J
- Liu Z.
first_author: Shen X
journal: Journal of pain research
year: 2025
volume: ''
issue: ''
pages: ''
doi: 10.2147/jpr.s540073
pmid: ''
type: Meta-analysis
topics:
- 颊针疗法
tags:
- pain_general;dysmenorrhea
evidence_level: na
oa_status: unknown
abstract: 'Objective: Primary dysmenorrhea (PD) is a recurrent disease. The current treatments for PD
  often fail to provide long-lasting effects, underscoring the necessity for new treatment options that
  can offer durable benefits. Previous studies have indicated that the durable effect of acupuncture for
  PD remains uncertain. In this review, we aimed to evaluate the durable effect after completion of treatment.Methods:
  Both English and Chinese literature were comprehensively retrieved from eight databases up to January
  24, 2025. Two independent reviewers conducted screening and data extraction. The risk'
url: https://doi.org/10.2147/jpr.s540073
pdf: null
language: en
status: draft
added_by: 颊针综述
added_date: '2026-09-09'
updated_date: '2026-09-09'
relevance: 3
