id: 2025-zhu-buccal-acupuncture-alleviates-postoperative
title: 'Buccal Acupuncture Alleviates Postoperative Pain in Patients Undergoing Radical Resection of Gastrointestinal
  Cancers: A Randomized Controlled Pilot Study.'
authors:
- Zhu ZX
- Chen C
- Zheng YF
- Gong WL
- Chen Z
- Fang SL
- Shao DH
- Sun CX.
first_author: Zhu ZX
journal: Chinese journal of integrative medicine
year: 2025
volume: ''
issue: ''
pages: ''
doi: 10.1007/s11655-025-4128-y
pmid: ''
type: RCT
topics:
- 颊针疗法
- 术后镇痛
tags:
- pain_general;postoperative;nausea_vomiting
evidence_level: na
oa_status: unknown
abstract: 'Objective: To preliminarily investigate the effect of buccal acupuncture therapy on ameliorating
  postoperative pain and enhancing recovery quality among patients undergoing radical resection of gastrointestinal
  cancers.Methods: Fifty-two participants were randomized at a 1:1 ratio to either the buccal acupuncture
  or the control group. The acupuncture protocol entailed targeting 5 predetermined acupoints [CA-2 (Upper
  jiao), CA-3 (Middle jiao), CA-4 (Lower jiao), CA-6 (back), and CA-7 (waist) and two adjustable acupoints
  [CA-1 (head) and CA-8 (sacrum)] on each side of the face. The outcomes incl'
url: https://doi.org/10.1007/s11655-025-4128-y
pdf: null
language: en
status: draft
added_by: 颊针综述
added_date: '2026-09-09'
updated_date: '2026-09-09'
relevance: 3
